# name: Architect Create Environment
# description: Easily register and deploy a component to the Architect Cloud
# author: architect-team
# branding:
#   icon: upload-cloud
#   color: green

# inputs:
#   ARCHITECT_USERNAME:
#     required: true
#   ARCHITECT_PASSWORD:
#     required: true
#   ARCHITECT_ACCOUNT:
#     required: true
#   ARCHITECT_ENVIRONMENT_NAME: # TODO: allow a user to specify the architect.yml filename
#     required: true # TODO: change to optional, default to unique name for PR
#   ARCHITECT_ENVIRONMENT_CONFIG: # TODO: remove in place of interfaces and params string
#     required: true
#   ARCHITECT_PLATFORM:
#     required: true

# # TODO: pass in param and interface string
# # deploy component name with tag that we assign, same name as the environment (tag should be the same as the env name by default)

# runs:
#   using: 'docker'
#   image: 'Dockerfile'
#   args:
#     - ${{ inputs.ARCHITECT_USERNAME }}
#     - ${{ inputs.ARCHITECT_PASSWORD }}
#     - ${{ inputs.ARCHITECT_ACCOUNT }}
#     - ${{ inputs.ARCHITECT_ENVIRONMENT_NAME }}
#     - ${{ inputs.ARCHITECT_ENVIRONMENT_CONFIG }} # TODO: config optional
#     - ${{ inputs.ARCHITECT_PLATFORM }}

name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: "composite"
  steps:
    - run: uname -orv
      shell: bash
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - run: echo "Nice to meet you!"
      shell: pwsh
