name: Create Preview
description: Easily register and deploy a component to a new environment on the Architect Cloud
author: architect-team
branding:
  icon: upload-cloud
  color: green

inputs:
  USERNAME:
    required: true
  PASSWORD:
    required: true
  ACCOUNT:
    required: true
  ENVIRONMENT:
    required: true
  PLATFORM:
    required: true
  COMPONENT_NAME: # TODO: use jq/yq and read from file?
    required: true
  DEPLOY_FLAGS:
    required: false
  COMPONENT_FILE:
    required: false
    default: ./architect.yml

runs:
  using: 'composite'
  steps:
    - run: npm install -g @architect-io/cli@0.6.1
      shell: bash
    - run: architect login -u ${{ inputs.USERNAME }} -p ${{ inputs.PASSWORD }}
      shell: bash
    - run: architect register ${{ inputs.COMPONENT_FILE }} -t ${{ inputs.ENVIRONMENT }}
      shell: bash
    - run: architect environment:create ${{ inputs.ENVIRONMENT }} -a ${{ inputs.ACCOUNT }} --platform ${{ inputs.PLATFORM }}
      shell: bash
    - run: architect deploy --auto_approve -a ${{ inputs.ACCOUNT }} -e ${{ inputs.ENVIRONMENT }} ${{ inputs.COMPONENT_NAME }}:${{ inputs.ENVIRONMENT }} ${{ inputs.DEPLOY_FLAGS }}
      shell: bash
