name: Architect Create Environment

inputs:
  ARCHITECT_USERNAME:
    required: true
  ARCHITECT_PASSWORD:
    required: true
  ARCHITECT_ACCOUNT:
    required: true
  ARCHITECT_PLATFORM:
    required: true
  ARCHITECT_ENVIRONMENT_CONFIG:
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ARCHITECT_USERNAME }}
    - ${{ inputs.ARCHITECT_PASSWORD }}
    - ${{ inputs.ARCHITECT_ACCOUNT }}
    - ${{ inputs.ARCHITECT_PLATFORM }}
    - ${{ inputs.ARCHITECT_ENVIRONMENT_CONFIG }}
