name: Architect Create Environment
description: Easily register and deploy a component to the Architect Cloud
author: architect-team
branding:
  icon: upload-cloud
  color: green

inputs:
  ARCHITECT_USERNAME:
    required: true
  ARCHITECT_PASSWORD:
    required: true
  ARCHITECT_ACCOUNT:
    required: true
  ARCHITECT_ENVIRONMENT: # TODO: allow a user to specify the architect.yml filename
    required: true # TODO: change to optional, default to unique name for PR
  # ARCHITECT_ENVIRONMENT_CONFIG_NAME: # TODO: remove in place of interfaces and params string
  #   required: true
  ARCHITECT_PLATFORM:
    required: true

# TODO: pass in param and interface string
# deploy component name with tag that we assign, same name as the environment (tag should be the same as the env name by default)
# TODO: env config optional

runs:
  using: 'composite'
  steps:
    - run: npm install -g @architect-io/cli
      shell: bash
    - run: architect version
      shell: bash
    - run: architect login -u ${{ inputs.ARCHITECT_USERNAME }} -p ${{ inputs.ARCHITECT_PASSWORD }}
      shell: bash
    - run: ls -la ./
      shell: bash
    - run: architect register ./architect.yml #  -t ${{ inputs.ARCHITECT_ENVIRONMENT_NAME }}
      shell: bash
      # TODO: keep using same name for tag and environment
    - run: architect environment:create ${{ inputs.ARCHITECT_ENVIRONMENT_NAME }} -a ${{ inputs.ARCHITECT_ACCOUNT }} --platform ${{ inputs.ARCHITECT_PLATFORM }}
      shell: bash
    - run: architect deploy --auto_approve -a ${{ inputs.ARCHITECT_ACCOUNT }} -e ${{ inputs.ARCHITECT_ENVIRONMENT_NAME }} ryan-cahill-a0/hello-world${{ inputs.ARCHITECT_ENVIRONMENT_NAME }}
      shell: bash
