name: Architect Create Preview
description: Easily register and deploy a component to a new environment on the Architect Cloud
author: architect-team
branding:
  icon: upload-cloud
  color: green

inputs:
  username:
    required: true
  password:
    required: true
  account:
    required: true
  environment:
    required: true
  platform:
    required: true
  component_name:
    required: true
  component_file:
    required: false
    default: ./architect.yml
  deploy_flags:
    required: false

runs:
  using: 'composite'
  steps:
    - run: npm install -g @architect-io/cli@0.6.3
      shell: bash
    - run: architect login -u ${{ inputs.username }} -p ${{ inputs.password }}
      shell: bash
    - run: architect register ${{ inputs.component_file }} -t ${{ inputs.environment }}
      shell: bash
    - run: architect environment:create ${{ inputs.environment }} -a ${{ inputs.account }} --platform ${{ inputs.platform }}
      shell: bash
    - run: architect deploy --auto_approve -a ${{ inputs.account }} -e ${{ inputs.environment }} ${{ inputs.component_name }}:${{ inputs.environment }} ${{ inputs.deploy_flags }}
      shell: bash
